#[doc = "Register `ETH_MTLISR` reader"]
pub struct R(crate::R<ETH_MTLISR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ETH_MTLISR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ETH_MTLISR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ETH_MTLISR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `Q0IS` reader - Queue interrupt status This bit indicates that an interrupt has been generated by Queue. To reset this bit, read ETH_MTLQICSR register to identify the interrupt cause and clear the source."]
pub type Q0IS_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Queue interrupt status This bit indicates that an interrupt has been generated by Queue. To reset this bit, read ETH_MTLQICSR register to identify the interrupt cause and clear the source."]
    #[inline(always)]
    pub fn q0is(&self) -> Q0IS_R {
        Q0IS_R::new((self.bits & 1) != 0)
    }
}
#[doc = "Interrupt status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [eth_mtlisr](index.html) module"]
pub struct ETH_MTLISR_SPEC;
impl crate::RegisterSpec for ETH_MTLISR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [eth_mtlisr::R](R) reader structure"]
impl crate::Readable for ETH_MTLISR_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets ETH_MTLISR to value 0"]
impl crate::Resettable for ETH_MTLISR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
